name: Deploy to Firebase Hosting on merge (Gradient)
on:
  push:
    branches:
      - gradient
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install && bun run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TALENTE_SPENDEN_WEBSITE }}
          channelId: live
          projectId: talente-spenden-website
          target: gradient
